//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dariosoft.EmailSender.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dariosoft.EmailSender.I18n.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is invalid..
        /// </summary>
        public static string Error_IncorrectCurrentPassword {
            get {
                return ResourceManager.GetString("Error_IncorrectCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user&apos;s password is invalid..
        /// </summary>
        public static string Error_Invalid_Current_User_Password {
            get {
                return ResourceManager.GetString("Error_Invalid_Current_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is not valid..
        /// </summary>
        public static string Error_InvalidEmailAddress {
            get {
                return ResourceManager.GetString("Error_InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the field &quot;@Field&quot; is invalid..
        /// </summary>
        public static string Error_InvalidFieldValue {
            get {
                return ResourceManager.GetString("Error_InvalidFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input data is invalid..
        /// </summary>
        public static string Error_InvalidInputData {
            get {
                return ResourceManager.GetString("Error_InvalidInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login. This account is disabled..
        /// </summary>
        public static string Error_LoginFailed_AccountIsDisable {
            get {
                return ResourceManager.GetString("Error_LoginFailed_AccountIsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login. This account is locked..
        /// </summary>
        public static string Error_LoginFailed_AccountIsLocked {
            get {
                return ResourceManager.GetString("Error_LoginFailed_AccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name or password is invalid..
        /// </summary>
        public static string Error_LoginFailed_InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("Error_LoginFailed_InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed due to an unexpected error. Retry to login after a few moment..
        /// </summary>
        public static string Error_LoginFailed_UnExpectedError {
            get {
                return ResourceManager.GetString("Error_LoginFailed_UnExpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of the field &quot;@Field&quot; is mandatory..
        /// </summary>
        public static string Error_MissingRequiredField {
            get {
                return ResourceManager.GetString("Error_MissingRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and the confirm password are not same. Enter a same password for them..
        /// </summary>
        public static string Error_NewPasswordAndConfirmPasswordAreNotSame {
            get {
                return ResourceManager.GetString("Error_NewPasswordAndConfirmPasswordAreNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record id is not provided to update the record..
        /// </summary>
        public static string Error_NoIdToUpdate {
            get {
                return ResourceManager.GetString("Error_NoIdToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate record: record with the same information already exists..
        /// </summary>
        public static string Error_RecordAlreadyExists {
            get {
                return ResourceManager.GetString("Error_RecordAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too simple. The minimum length of password is @Len characters  and it must contains at least one digit and one letter..
        /// </summary>
        public static string Error_TooSimplePassword {
            get {
                return ResourceManager.GetString("Error_TooSimplePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the record. The record is in use..
        /// </summary>
        public static string Error_UnableToDelete_RecordInuse {
            get {
                return ResourceManager.GetString("Error_UnableToDelete_RecordInuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed due to an unexpected error..
        /// </summary>
        public static string Error_UnexpectedError {
            get {
                return ResourceManager.GetString("Error_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username(&quot;@UserName&quot;) is already reserved by someone else..
        /// </summary>
        public static string Error_UserNameIsReserved {
            get {
                return ResourceManager.GetString("Error_UserNameIsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string Info_PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("Info_PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delete operation has been done successfully..
        /// </summary>
        public static string Info_SuccessDeleteMessage {
            get {
                return ResourceManager.GetString("Info_SuccessDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has been done successfully..
        /// </summary>
        public static string Info_SuccessMessage {
            get {
                return ResourceManager.GetString("Info_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records were affected..
        /// </summary>
        public static string Warning_NoRecordsAffected {
            get {
                return ResourceManager.GetString("Warning_NoRecordsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        public static string Warning_RecordNotFound {
            get {
                return ResourceManager.GetString("Warning_RecordNotFound", resourceCulture);
            }
        }
    }
}
